import '../styles/globalStyles.scss';
import { setUpPiniaReplicants, setUpReplicants } from '../helpers/storeHelper';
import Panel from './matchManager.vue';
import { createApp } from 'vue';
import { tournamentDataReps, tournamentDataStore, tournamentDataStoreKey } from '../store/tournamentDataStore';
import { activeRoundReps, useActiveRoundStore } from '../store/activeRoundStore';
import { castersReps, useCasterStore } from '../store/casterStore';
import { scoreboardReps, scoreboardStore, scoreboardStoreKey } from '../store/scoreboardStore';
import { setUpErrorHandler } from '../store/errorHandlerStore';
import { nextRoundReps, useNextRoundStore } from '../store/nextRoundStore';
import { settingsReps, settingsStore, settingsStoreKey } from '../settings/settingsStore';
import { obsReps, useObsStore } from '../store/obsStore';
import { createPinia } from 'pinia';

(async () => {
    await setUpReplicants(tournamentDataReps, tournamentDataStore);
    await setUpReplicants(scoreboardReps, scoreboardStore);
    await setUpReplicants(settingsReps, settingsStore);
    const app = createApp(Panel);
    app.use(createPinia());
    await setUpPiniaReplicants(obsReps, useObsStore());
    await setUpPiniaReplicants(nextRoundReps, useNextRoundStore());
    await setUpPiniaReplicants(activeRoundReps, useActiveRoundStore());
    setUpErrorHandler(app);
    await setUpPiniaReplicants(castersReps, useCasterStore());
    app.use(tournamentDataStore, tournamentDataStoreKey);
    app.use(scoreboardStore, scoreboardStoreKey);
    app.use(settingsStore, settingsStoreKey);
    app.mount('#app');
})();
