/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Rounds {
	[k: string]: Round;
}
export interface Round {
	meta?: {
		name?: string;
		[k: string]: any;
	};
	games?: Game[];
	[k: string]: any;
}
export interface Game {
	stage?: string;
	mode?: string;
	[k: string]: any;
}
