/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Used for storing tournament meta data such as IDs
 */
export interface TournamentDataSource {
	/**
	 * Provider that tournament data is coming from
	 */
	dataProvider?: 'battlefy' | 'smashgg' | 'radia';
	/**
	 * Tournament ID used by provider
	 */
	tournamentID?: string | null;
	/**
	 * Stage ID used by provider
	 */
	stageID?: string[];
	[k: string]: any;
}
