/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BundleDeclaredConfig {
	[k: string]: {
		scenes?: {
			value: string;
			names?: TranslatableNames;
		}[];
		casterSets?: {
			key: string;
			maxItems: number;
			names?: TranslatableNames;
		}[];
	};
}
export interface TranslatableNames {
	EN?: string;
	JA?: string;
	[k: string]: string;
}
