/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BundleCasterSets {
	[k: string]: {
		[k: string]: {
			[k: string]: Caster;
		};
	};
}
export interface Caster {
	name: string;
	twitter: string;
	pronouns: string;
	imageUrl?: string;
	videoUrl?: string;
}
