/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type GameData =
	| []
	| [
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			}
	  ]
	| [
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			}
	  ]
	| [
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			}
	  ]
	| [
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			}
	  ]
	| [
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			}
	  ]
	| [
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			}
	  ]
	| [
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			},
			{
				winner: 'none' | 'alpha' | 'bravo';
				color?: {
					index: number;
					title: string;
					clrA: string;
					clrB: string;
					clrNeutral: string;
					categoryName: string;
					isCustom: boolean;
					[k: string]: unknown;
				} & {
					colorsSwapped: boolean;
					[k: string]: unknown;
				};
				[k: string]: unknown;
			}
	  ];
