/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HighlightedMatches = Match[];

export interface Match {
	meta: {
		name: string;
		/**
		 * Name to be automatically assigned as the name of the next match on graphics
		 */
		shortName: string;
		/**
		 * ID of the match, for Battlefy use _id
		 */
		id: string;
		/**
		 * Name of the stage match originates from
		 */
		stageName?: string;
		/**
		 * The time the set was completed at, null if yet to be completed, Stored in ISO format
		 */
		completionTime?: string;
		/**
		 * Round number from provider
		 */
		round?: number;
		/**
		 * Match number from provider
		 */
		match?: number;
		playType?: 'BEST_OF' | 'PLAY_ALL';
	};
	teamA: Team;
	teamB: Team;
}
export interface Team {
	id: string;
	name: string;
	logoUrl?: string;
	showLogo: boolean;
	players: Player[];
	[k: string]: unknown;
}
export interface Player {
	name: string;
	[k: string]: unknown;
}
