/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type LastFmNowPlaying = SongInfo & {
	album?: string;
	cover?: string;
	artistSong?: string;
	[k: string]: unknown;
};

export interface SongInfo {
	artist?: string;
	song: string;
	[k: string]: unknown;
}
