/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NextRound {
	teamA: {
		id: string;
		name: string;
		logoUrl?: string;
		showLogo: boolean;
		players: {
			name: string;
			[k: string]: any;
		}[];
		[k: string]: any;
	};
	teamB: {
		id: string;
		name: string;
		logoUrl?: string;
		showLogo: boolean;
		players: {
			name: string;
			[k: string]: any;
		}[];
		[k: string]: any;
	};
	round: {
		id: string;
		name: string;
	};
	games: {
		stage: string;
		mode: string;
		[k: string]: any;
	}[];
}
