/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NextTeams {
	teamAInfo?: {
		id: string;
		name: string;
		logoUrl?: string;
		players: {
			name: string;
			[k: string]: any;
		}[];
		[k: string]: any;
	};
	teamBInfo?: {
		id: string;
		name: string;
		logoUrl?: string;
		players: {
			name: string;
			[k: string]: any;
		}[];
		[k: string]: any;
	};
}
