/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ObsConfig = ObsConfigItem[];

export interface ObsConfigItem {
	sceneCollection: string;
	gameplayInput?: string;
	gameplayScene?: string;
	intermissionScene?: string;
}
