/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ObsData {
	status: 'CONNECTED' | 'CONNECTING' | 'NOT_CONNECTED';
	scenes?: string[];
	transitions?: string[];
	gameplayScene?: string;
	intermissionScene?: string;
}
