/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ObsState {
	enabled: boolean;
	status: 'CONNECTED' | 'CONNECTING' | 'NOT_CONNECTED';
	scenes?: string[];
	inputs?: {
		name: string;
		uuid?: string | null;
		noVideoOutput: boolean;
	}[];
	currentScene?: string;
	currentSceneCollection?: string;
}
