/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PredictionStore {
	/**
	 * If Predictions should be enabled for current settings
	 */
	enablePrediction: boolean;
	/**
	 * Twitch Prediction instance
	 */
	currentPrediction?: {
		/**
		 * Twitch ID of the Prediction.
		 */
		id: string;
		/**
		 * Twitch ID of the broadcaster
		 */
		broadcaster_id: string;
		/**
		 * Twitch User Login
		 */
		broadcaster_name: string;
		/**
		 * Twitch user Display Name
		 */
		broadcaster_login: string;
		/**
		 * Title of prediction
		 */
		title: string;
		/**
		 * ID of wining ID
		 */
		winning_outcome_id: string | null;
		/**
		 * Array of possible outcomes for the Prediction
		 */
		outcomes: {
			id: string;
			title: string;
			users: number;
			channel_points: number;
			top_predictors: {
				user_id: string;
				user_login: string;
				user_name: string;
				channel_points_used: number;
				channel_points_won: number;
			}[];
			color: 'BLUE' | 'PINK';
		}[];
		/**
		 * Total duration for the Prediction (in seconds)
		 */
		prediction_window: number;
		/**
		 * Status of the Prediction
		 */
		status: 'RESOLVED' | 'ACTIVE' | 'CANCELED' | 'LOCKED';
		/**
		 * UTC timestamp for the Prediction’s start time
		 */
		created_at: string;
		/**
		 * UTC timestamp for when the Prediction ended, null if ACTIVE
		 */
		ended_at: string | null;
		/**
		 * UTC timestamp for when the Prediction was locked, null if not LOCKED
		 */
		locked_at: string | null;
	};
}
