/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PredictionStore {
	/**
	 * If Predictions should be enabled for current settings
	 */
	enablePrediction: boolean;
	currentPrediction?: Prediction;
}
/**
 * Twitch Prediction instance
 */
export interface Prediction {
	/**
	 * Twitch ID of the Prediction.
	 */
	id: string;
	/**
	 * Twitch ID of the broadcaster
	 */
	broadcasterId: string;
	/**
	 * Twitch User Login
	 */
	broadcasterName: string;
	/**
	 * Twitch user Display Name
	 */
	broadcasterLogin: string;
	/**
	 * Title of prediction
	 */
	title: string;
	/**
	 * ID of winning outcome
	 */
	winningOutcome: string | null;
	/**
	 * Array of possible outcomes for the Prediction
	 */
	outcomes: {
		id: string;
		title: string;
		users: number;
		pointsUsed: number;
		topPredictors: {id: string; login: string; username: string; pointsUsed: number; pointsWon: number}[];
		color: 'BLUE' | 'PINK';
	}[];
	/**
	 * Total duration for the Prediction (in seconds)
	 */
	duration: number;
	/**
	 * Status of the Prediction
	 */
	status: 'RESOLVED' | 'ACTIVE' | 'CANCELED' | 'LOCKED';
	/**
	 * UTC timestamp for the Prediction’s start time
	 */
	createdAt: string;
	/**
	 * UTC timestamp for when the Prediction ended, null if ACTIVE
	 */
	endedAt: string | null;
	/**
	 * UTC timestamp for when the Prediction was locked, null if not LOCKED
	 */
	lockedAt: string | null;
}
