/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Rounds {
	[k: string]: {
		meta?: {
			name?: string;
			[k: string]: any;
		};
		games?: {
			stage?: string;
			mode?: string;
			[k: string]: any;
		}[];
		[k: string]: any;
	};
}
