/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RuntimeConfig {
	gameVersion: 'SPLATOON_2' | 'SPLATOON_3';
	locale: 'EN' | 'DE' | 'EU_FR' | 'JA';
}
