/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TournamentData {
	meta?: {
		id?: string;
		[k: string]: any;
	};
	data?: Team[];
	[k: string]: any;
}
export interface Team {
	id?: string;
	name?: string;
	logoUrl?: string;
	players?: Player[];
}
export interface Player {
	name?: string;
}
