name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout nodecg/nodecg
        uses: actions/checkout@v2
        with:
          token: ${{ secrets['GITHUB_TOKEN'] }}
          repository: nodecg/nodecg
          path: ./nodecg-temp

      - name: Copy ./nodecg-temp > ./nodecg
        run: cp -r ./nodecg-temp ./nodecg

      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets['GITHUB_TOKEN'] }}
          ref: ${{ github.ref }}
          fetch-depth: 0
          path: ./nodecg/bundles/ipl-overlay-controls

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up NPM cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Update NPM
        run: npm install -g npm@7.7.0

      - name: Install NPM dependencies
        working-directory: ./nodecg/bundles/ipl-overlay-controls
        run: npm ci

      - name: Run ESLint on source
        working-directory: ./nodecg/bundles/ipl-overlay-controls
        run: npm run lint

      - name: Build
        if: github.ref == 'refs/heads/master'
        working-directory: ./nodecg/bundles/ipl-overlay-controls
        run: |
          npm run clean
          npm run build

      - name: Set up GitHub for SSH access
        if: github.ref == 'refs/heads/master'
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets['GH_SSH'] }}

      - name: Set git config
        if: github.ref == 'refs/heads/master'
        working-directory: ./nodecg/bundles/ipl-overlay-controls
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Merge master branch into build branch
        if: github.ref == 'refs/heads/master'
        continue-on-error: true
        working-directory: ./nodecg/bundles/ipl-overlay-controls
        run: |
          git checkout master
          git checkout build
          git merge master

      - name: Commit built files
        if: github.ref == 'refs/heads/master'
        id: commit
        continue-on-error: true
        working-directory: ./nodecg/bundles/ipl-overlay-controls
        run: |
          git add -f dashboard extension
          git commit -m "Build result from master branch" -a

      - name: Push built files to "build" branch
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets['GITHUB_TOKEN'] }}
          branch: build
          directory: ./nodecg/bundles/ipl-overlay-controls
